### ISSUE TITLE
panic: empty value

### ISSUE THREAD

**Issue by sg-qwt** [starudream/douyu-task#35]
你好

谢谢新增的config flag，发现更新了v3.0.0之后送礼物会panic，不过实际上礼物已经送出去了。

cfg.yaml:
```
{"cron":{"refresh":"0 10 0 * * *","renewal":"0 50 23 * * *"},"douyu":{"assigns":[{"all":true,"room":500269}],"did":"xxx","ignore_expired_check":true,"ltp0":"xxx","room":9999}}
```

复现如下：

```
> ./result/bin/douyu-task run gift send 500269 268 50 --config ./cfg.yaml 


send gift to room id 500269, gift id 268, count 50, confirm? (y/n)y
panic: empty value

goroutine 1 [running]:
github.com/starudream/douyu-task/api.(*Gifts).TableString.Structs.func1(0xa75b60?)
	github.com/starudream/go-lib/tablew/v2@v2.0.3/helper.go:20 +0x36
github.com/starudream/go-lib/tablew/v2.Render(0xc000259a60)
	github.com/starudream/go-lib/tablew/v2@v2.0.3/helper.go:11 +0x48
github.com/starudream/go-lib/tablew/v2.Structs(...)
	github.com/starudream/go-lib/tablew/v2@v2.0.3/helper.go:17
github.com/starudream/douyu-task/api.(*Gifts).TableString(0xc0002f2900?)
	github.com/starudream/douyu-task/api/gift.go:20 +0x54
main.glob..func7.1(0xc0002bfc00?, {0xc0002b14f0, 0x3, 0x5})
	github.com/starudream/douyu-task/cmd/run.go:97 +0x5ab
github.com/spf13/cobra.(*Command).execute(0xc00031f500, {0xc0002b14a0, 0x5, 0x5})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00031e300)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x408fc5?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	github.com/starudream/douyu-task/cmd/main.go:8 +0x1a
```

**Comment by starudream** [comment]
感谢反馈，已修复 [v3.0.1](https://github.com/starudream/douyu-task/releases/tag/v3.0.1)
